import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Header from '@/components/Header'
import { ThemeProvider } from '@/components/theme'
// import { authMiddleware } from "@clerk/nextjs";
import {Toaster} from "react-hot-toast";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MeghDoot~Vault',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (


      <ClerkProvider>
          <html lang="en">
            <body className={inter.className}>

            <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

{/* this ThemeProvider above will get the default system's theme for us
its a functionality for us from the 'ShadCN' Ui/Ux framework */}

              <Header />

              {children}
             
             <Toaster position='top-center' />
             </ThemeProvider>

              </body>
            {/* so this {children} is wer the page is gng to get injected  */}
          </html>
      </ClerkProvider>

  )
}
